### ISSUE TITLE
idea 2024.3.1 is not work

### ISSUE THREAD

**Issue by Aurorxa** [Gyeom/dependency-explorer#11]

**Comment by Aurorxa** [comment]
My environment is as follows：
* OS version is win11 24H2
![image](https://github.com/user-attachments/assets/8d556dcd-7a20-4be9-b42d-6ef7dc2d984a)
* IDEA version is 2024.3.1 
![image](https://github.com/user-attachments/assets/4354a9fb-b0cf-452e-ba76-03d4e9e52f3a)
* Gradle version is 8.7
![image](https://github.com/user-attachments/assets/093b2bec-e0f7-44f8-9e9a-8d22a063b63d)
* JDK version is 17
![image](https://github.com/user-attachments/assets/2bb60811-fda7-4d12-9440-737049db1ebb)

However, the plugin has no effect

![image](https://github.com/user-attachments/assets/2cfdf222-2b27-4dd3-b662-7201fa1c05ac)

the plugin is enabled

![image](https://github.com/user-attachments/assets/f06d4c9f-938e-463e-89a6-5109c5219613)

**Comment by Gyeom** [comment]
Can you show the entire implementation statement? Part of it seems to be hidden.

<img width="938" alt="image" src="https://github.com/user-attachments/assets/51a8be7c-2569-4174-8d5f-ea0cce8a23c4" />

**Comment by Aurorxa** [comment]
OK，my project is https://github.com/Aurorxa/java-base , Previously it was because I set it to private, now it is set to public

build.gradle content is follow ：

```grovvy
plugins {
    id 'java'
}

group = 'com.github'
version = '1.0'

repositories {
    // 阿里云中央仓库
    maven {
        url 'https://maven.aliyun.com/repository/public'
    }
    // 阿里云 Apache Snapshots 仓库
    maven {
        url 'https://maven.aliyun.com/repository/apache-snapshots'
    }

    // 阿里云 Google 仓库
    maven {
        url 'https://maven.aliyun.com/repository/google'
    }

    // 阿里云 Gradle Plugin 仓库
    maven {
        url 'https://maven.aliyun.com/repository/gradle-plugin'
    }
    mavenLocal()
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.11.3')
    testImplementation 'org.junit.jupiter:junit-jupiter:5.11.3'
    implementation "commons-io:commons-io:2.18.0"
    compileOnly 'org.projectlombok:lombok:1.18.36'
    annotationProcessor 'org.projectlombok:lombok:1.18.36'
    implementation 'org.springframework.boot:spring-boot-starter-web:3.4.0'

    testCompileOnly 'org.projectlombok:lombok:1.18.36'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.36'
}

test {
    useJUnitPlatform()
}
```

**Comment by Aurorxa** [comment]
![image](https://github.com/user-attachments/assets/1fbad843-e6a9-4dec-b918-c3cef8c5bc8c)

**Comment by Gyeom** [comment]
@Aurorxa 

Thank you for explaining the issue in detail.

We have fixed the bug and applied the changes in version 1.3.0.

Could you please update to the latest version and verify if the issue is resolved?

**Comment by Aurorxa** [comment]
thank you，i try it tomorrow，good night！

**Comment by Aurorxa** [comment]
In windows sanbox I simulated a completely new environment
![image](https://github.com/user-attachments/assets/bc09669b-2f46-40cd-8e82-9c9b2de44d6c)
but it is not work
![image](https://github.com/user-attachments/assets/e27804d6-cac8-44de-8af7-9d4fe104e7cf)

**Comment by Gyeom** [comment]
@Aurorxa 

I finally found the cause of the bug and fixed it in version 1.7.0.

You were a great help. Thank you so much!

**Comment by Aurorxa** [comment]
I have updated the plugin and found it works, very good, thanks

**Comment by Gyeom** [comment]
@Aurorxa 

I’m the one who’s truly grateful.
If you have a moment, I would greatly appreciate it if you could leave us a review and a rating. Thank you very much!
